/*
 * Data Center Power & Energization — dataset
 * As-of: May 2026. Figures are point-in-time estimates drawn from IEA, JLL,
 * company disclosures and industry/press reporting. Verify before decisions.
 */

// ---------------------------------------------------------------------------
// Demand scenarios (IEA, global data center electricity, TWh)
// ---------------------------------------------------------------------------
const DEMAND = {
  years: [2024, 2025, 2030, 2035],
  scenarios: {
    "Base Case":      [415, 485, 945, 1193],
    "Lift-Off":       [415, 485, 1008, 1637],
    "High Efficiency":[415, 485, 868, 1013],
    "Headwinds":      [415, 485, 833, 942],
  },
  // Capacity (GW) installed base, JLL
  capacity: { years: [2025, 2030], gw: [103, 200] },
  // AI share of data center workloads (%)
  aiShare: { years: [2025, 2027, 2030], pct: [25, 45, 50] },
  notes: [
    "2024 ≈ 415 TWh (~1.5% of global electricity); grew ~17% to ~485 TWh in 2025.",
    "Base Case roughly doubles to ~945 TWh by 2030 (~3% of global electricity), ~15%/yr growth.",
    "Capacity ~doubles to ~200 GW by 2030 (~14% CAGR), ~97–100 GW added.",
    "AI ≈ 25% of workloads in 2025 → ~50% by 2030; inference overtakes training ~2027.",
    "Interconnection waits exceed ~4 years in primary US markets — the binding constraint.",
  ],
};

const KPIS = [
  { label: "Global DC electricity, 2025", value: "~485 TWh", sub: "+17% YoY (IEA)" },
  { label: "Projected 2030 (Base Case)", value: "~945 TWh", sub: "~3% of global power" },
  { label: "Capacity by 2030", value: "~200 GW", sub: "~14% CAGR, ~2x" },
  { label: "AI share of workloads 2030", value: "~50%", sub: "inference-led from 2027" },
  { label: "Gas-turbine backlog", value: "3–5 yrs", sub: "sold out to ~2028" },
  { label: "Grid interconnection wait", value: ">4 yrs", sub: "primary US markets" },
];

// ---------------------------------------------------------------------------
// Technology stack (sorted by time-to-power tier)
// ---------------------------------------------------------------------------
const TECHNOLOGIES = [
  { name: "Fuel cells (SOFC)", tier: 1, ttp: "≈55–90 days", capex: "$3,000–4,000/kW",
    emissions: "Very low local (no combustion)", readiness: "Commercial",
    players: ["Bloom Energy"],
    note: "Fastest viable energization where air permitting is the binding constraint." },
  { name: "Linear generators (multi-fuel)", tier: 1, ttp: "Months", capex: "Moderate",
    emissions: "Near-zero NOx, no after-treatment", readiness: "Early commercial",
    players: ["Mainspring Energy"],
    note: "Gas/biogas/propane/hydrogen; fast start/ramp; factory-built modular." },
  { name: "Rental / mobile gensets", tier: 1, ttp: "Weeks", capex: "Low (opex-heavy)",
    emissions: "High (diesel)", readiness: "Commercial",
    players: ["Aggreko", "Cat Rental"],
    note: "Bridge power while permanent assets are built." },
  { name: "Reciprocating gas engines", tier: 2, ttp: "≈18 months", capex: "Lower upfront",
    emissions: "Moderate", readiness: "Commercial",
    players: ["Caterpillar", "INNIO Jenbacher", "Wärtsilä", "Rolls-Royce (mtu)", "Cummins"],
    note: "Baseload + backup; modular; shorter lead than turbines." },
  { name: "Aeroderivative gas turbines", tier: 2, ttp: "1–2 years", capex: "Moderate",
    emissions: "Moderate", readiness: "Commercial",
    players: ["Solar Turbines (Caterpillar)", "GE Vernova (LM)", "Siemens Energy"],
    note: "Faster, skid-mounted vs heavy-duty." },
  { name: "Solar + wind + storage", tier: 2, ttp: "1–3 years", capex: "Falling",
    emissions: "Zero (variable)", readiness: "Commercial",
    players: ["NextEra", "Amazon (self-build)"],
    note: "Needs firming; pairs with BESS." },
  { name: "Turnkey gas microgrid", tier: 2, ttp: "12–24 months", capex: "Power-agreement (PaaS)",
    emissions: "Lower than diesel", readiness: "Commercial",
    players: ["VoltaGrid", "ProEnergy", "Mainspring Energy"],
    note: "Single power agreement: fuel + generation + O&M." },
  { name: "Heavy-duty gas turbine (H-class)", tier: 3, ttp: "3–5 years", capex: "High",
    emissions: "Moderate (CCGT efficient)", readiness: "Commercial (sold out)",
    players: ["GE Vernova", "Siemens Energy", "Mitsubishi Heavy Industries"],
    note: ">600 MW, >65% CCGT efficiency; order books full to ~2028–2030." },
  { name: "Nuclear — existing / restart / uprate", tier: 3, ttp: "1–4 years (restart)", capex: "High",
    emissions: "Zero", readiness: "Commercial",
    players: ["Constellation", "Vistra", "Talen", "NextEra", "Dominion"],
    note: "Fastest firm carbon-free route via restarts, uprates, life extension." },
  { name: "Nuclear — SMR / microreactor", tier: 3, ttp: "2030+", capex: "High (FOAK)",
    emissions: "Zero", readiness: "Pre-commercial",
    players: ["TerraPower", "Oklo", "X-energy", "Kairos Power", "NuScale", "Westinghouse", "Radiant"],
    note: "Long-term prize; <2 GW likely online before ~2033." },
  { name: "Battery storage (BESS)", tier: 2, ttp: "Months–1 year", capex: "Falling",
    emissions: "Zero (operation)", readiness: "Commercial",
    players: ["Tesla", "Fluence", "Multiple"],
    note: "~20–25 GW paired with DCs by 2030; smooths AI power swings." },
];

const TIER_LABELS = {
  1: "Tier 1 · Immediate (months)",
  2: "Tier 2 · Medium (1–3 yrs)",
  3: "Tier 3 · Long horizon (3+ yrs / 2030+)",
};

// ---------------------------------------------------------------------------
// Companies
// segment ∈ Utility | IPP | Turbine OEM | Engine/Distributed | BTM Integrator
//          | Nuclear/SMR | Electrical Equipment | EPC/Dev | Capital | Fuel/Midstream
// ---------------------------------------------------------------------------
const COMPANIES = [
  // IPPs
  { name: "Constellation Energy", ticker: "CEG", segment: "IPP", tier: 3,
    tech: ["Nuclear (existing/restart)"], ownership: "Public", region: "US",
    metric: "~60 GW fleet (largest US nuclear)",
    deals: ["Microsoft TMI/Crane restart (835 MW, ~2027)", "Meta Clinton (1.1 GW, 20-yr)"],
    moat: "Largest US nuclear fleet; restart optionality; firm carbon-free.",
    note: "Most leveraged to firm-power scarcity." },
  { name: "Vistra", ticker: "VST", segment: "IPP", tier: 3,
    tech: ["Nuclear", "Gas"], ownership: "Public", region: "US",
    metric: "~45 GW fleet",
    deals: ["Meta — Perry, Davis-Besse, Beaver Valley (~2.2 GW + uprates)"],
    moat: "Nuclear + gas fleet; capacity revenue locked through 2028.",
    note: "" },
  { name: "Talen Energy", ticker: "TLN", segment: "IPP", tier: 3,
    tech: ["Nuclear"], ownership: "Public", region: "US",
    metric: "~13 GW fleet",
    deals: ["AWS — Susquehanna (~1.92 GW, 17-yr PPA to 2042)"],
    moat: "Co-located nuclear adjacency to PJM data center demand.",
    note: "Deal shifted BTM → front-of-meter after FERC concerns." },
  { name: "NRG Energy", ticker: "NRG", segment: "IPP", tier: 2,
    tech: ["Gas"], ownership: "Public", region: "US",
    metric: "~28 GW fleet",
    deals: [], moat: "Merchant gas capacity in tight markets.", note: "" },
  { name: "NextEra Energy", ticker: "NEE", segment: "IPP", tier: 2,
    tech: ["Renewables", "Nuclear"], ownership: "Public", region: "US",
    metric: "Largest US renewables operator",
    deals: ["Google — Duane Arnold restart study (~601 MW)"],
    moat: "Scale in solar+storage + nuclear restarts.", note: "" },

  // Turbine OEMs
  { name: "GE Vernova", ticker: "GEV", segment: "Turbine OEM", tier: 3,
    tech: ["Heavy-duty gas turbine", "Aeroderivative"], ownership: "Public", region: "Global",
    metric: "~80 GW orderbook; powers ~50% of US electrons",
    deals: ["~20–33% of slot reservations tied to AI/hyperscalers"],
    moat: "One of three large-turbine makers; controls scarce slots.",
    note: "Sold out to ~2028; capacity additions mostly post-2028." },
  { name: "Siemens Energy", ticker: "ENR", segment: "Turbine OEM", tier: 3,
    tech: ["Heavy-duty gas turbine", "Grid"], ownership: "Public", region: "Global",
    metric: "Record backlog ~€146B",
    deals: ["Quoting 2029–2030 delivery slots"],
    moat: "Big-three turbine maker + grid equipment.", note: "" },
  { name: "Mitsubishi Heavy Industries", ticker: "7011.T", segment: "Turbine OEM", tier: 3,
    tech: ["Heavy-duty gas turbine"], ownership: "Public", region: "Global",
    metric: "Energy bookings +45% YoY",
    deals: ["Most slots booked 2027–2028; doubling capacity"],
    moat: "Big-three turbine maker.", note: "" },

  // Engine / distributed OEMs
  { name: "Caterpillar", ticker: "CAT", segment: "Engine/Distributed", tier: 2,
    tech: ["Recip gas engine", "Aeroderivative (Solar Turbines)"], ownership: "Public", region: "Global",
    metric: "Solar Turbines expanding capacity ~2.5x",
    deals: ["Agreements with Vertiv and Joule Capital Partners"],
    moat: "Broad engine + turbine portfolio; service network.", note: "" },
  { name: "Cummins", ticker: "CMI", segment: "Engine/Distributed", tier: 2,
    tech: ["Recip gas/diesel engine", "Backup gensets"], ownership: "Public", region: "Global",
    metric: "Major genset supplier", deals: [],
    moat: "Backup/prime power gensets at scale.", note: "" },
  { name: "INNIO Jenbacher", ticker: "Private (Advent)", segment: "Engine/Distributed", tier: 2,
    tech: ["Recip gas engine"], ownership: "Private", region: "Global",
    metric: "Mega-orders for data center power",
    deals: ["VoltaGrid — 1.5 GW behind-the-meter engine order"],
    moat: "High-efficiency gas engines; hydrogen-capable.", note: "" },
  { name: "Wärtsilä", ticker: "WRT1V.HE", segment: "Engine/Distributed", tier: 2,
    tech: ["Recip gas engine"], ownership: "Public", region: "Global",
    metric: "Energy division +29% sales (Q4 2025)", deals: [],
    moat: "Flexible balancing engines + storage.", note: "" },
  { name: "Rolls-Royce Power Systems (mtu)", ticker: "RR.L", segment: "Engine/Distributed", tier: 2,
    tech: ["Recip gas engine", "Backup"], ownership: "Public", region: "Global",
    metric: "DC power gen products +~50%", deals: [],
    moat: "mtu engines; data center backup pedigree.", note: "" },

  // BTM Integrators / onsite power-as-a-service
  { name: "Bloom Energy", ticker: "BE", segment: "BTM Integrator", tier: 1,
    tech: ["Fuel cells (SOFC)"], ownership: "Public", region: "US/Global",
    metric: "55-day delivery record; stock +150% YTD",
    deals: ["Oracle (up to 2.8 GW MSA; 1.2 GW deploying)", "Brookfield ($5B AI-factory partnership)",
            "CoreWeave (~850 MW operating)", "Nebius (250 MW / $2.6B over decade)"],
    moat: "Fastest energization; sidesteps combustion permitting.",
    note: "Leading near-term onsite technology." },
  { name: "Mainspring Energy", ticker: "Private", segment: "BTM Integrator", tier: 1,
    tech: ["Linear generators"], ownership: "Private", region: "US",
    metric: "Factory-built, multi-fuel modular",
    deals: [], moat: "Near-zero NOx, no after-treatment; fuel-flexible.",
    note: "Deploys in months; islanding capable." },
  { name: "VoltaGrid", ticker: "Private", segment: "BTM Integrator", tier: 2,
    tech: ["Turnkey gas microgrid", "Hybrid + storage"], ownership: "Private", region: "US/Global",
    metric: "$5B financing; $1B equity (Blackstone+Halliburton)",
    deals: ["Halliburton JV — 400 MW (2028, Eastern Hemisphere)", "INNIO — 1.5 GW engines",
            "ABB partnership", "Oracle collaboration"],
    moat: "Turnkey power agreement (power+fuel+logistics); global reach via Halliburton.",
    note: "Targeting Middle East / Eastern Hemisphere first." },
  { name: "ProEnergy", ticker: "Private", segment: "BTM Integrator", tier: 2,
    tech: ["Aeroderivative", "Modular plant"], ownership: "Private", region: "US",
    metric: "Fast-track modular gas plants",
    deals: [], moat: "Repowered aero turbines for fast deployment.", note: "" },

  // Nuclear / SMR developers
  { name: "TerraPower", ticker: "Private (Gates)", segment: "Nuclear/SMR", tier: 3,
    tech: ["SMR (Natrium)"], ownership: "Private", region: "US",
    metric: "First NRC construction permit (2026); ~345 MW Natrium",
    deals: ["Meta — 2 Natrium units (~690 MWe) + rights to ~2.1 GW by 2035"],
    moat: "Sodium-cooled + molten-salt storage; Gates-backed.",
    note: "Wyoming project targeting ops ~2031–2032." },
  { name: "Oklo", ticker: "OKLO", segment: "Nuclear/SMR", tier: 3,
    tech: ["Microreactor (Aurora)"], ownership: "Public", region: "US",
    metric: "Build-own-operate model",
    deals: ["Meta (~0.75–1.2 GW, Ohio)", "Switch framework", "Equinix (500 MW)"],
    moat: "Sell power not reactors; early DC relationships.",
    note: "Commercial deployment early 2030s." },
  { name: "X-energy", ticker: "Private", segment: "Nuclear/SMR", tier: 3,
    tech: ["SMR (Xe-100)"], ownership: "Private", region: "US",
    metric: "Up to 12× Xe-100 with Amazon",
    deals: ["Amazon — ~$700M / $500M round; SMR development"],
    moat: "HTGR pebble-bed; Amazon-backed.", note: "" },
  { name: "Kairos Power", ticker: "Private", segment: "Nuclear/SMR", tier: 3,
    tech: ["SMR (KP-FHR)"], ownership: "Private", region: "US",
    metric: "NRC construction permit (Hermes, 2023)",
    deals: ["Google — first corporate SMR fleet (50 → ~500 MW by 2035)"],
    moat: "Fluoride-salt-cooled high-temp reactor; Google partner.", note: "" },
  { name: "NuScale Power", ticker: "SMR", segment: "Nuclear/SMR", tier: 3,
    tech: ["SMR"], ownership: "Public", region: "US/Global",
    metric: "Only NRC-approved SMR design",
    deals: ["Romania deployment (first module ~2033)"],
    moat: "Design certification lead.", note: "" },
  { name: "Westinghouse", ticker: "Private (Cameco/Brookfield)", segment: "Nuclear/SMR", tier: 3,
    tech: ["AP300 SMR", "eVinci microreactor", "AP1000"], ownership: "Private", region: "Global",
    metric: "Established reactor vendor",
    deals: [], moat: "Large installed base + new SMR designs.", note: "" },
  { name: "Radiant", ticker: "Private", segment: "Nuclear/SMR", tier: 3,
    tech: ["Microreactor (Kaleidos)"], ownership: "Private", region: "US",
    metric: "Portable microreactor",
    deals: ["Equinix — preorder (20× Kaleidos units)"],
    moat: "Transportable microreactor for distributed sites.", note: "" },
  { name: "Dominion Energy", ticker: "D", segment: "Nuclear/SMR", tier: 3,
    tech: ["Nuclear", "Utility"], ownership: "Public", region: "US",
    metric: "Serves Data Center Alley (Virginia)",
    deals: ["Amazon — Lake Anna SMR study", "Meta — multiple"],
    moat: "Owns the grid in the largest US DC market.", note: "" },

  // Electrical equipment (inside-the-fence)
  { name: "ABB", ticker: "ABBN.SW", segment: "Electrical Equipment", tier: 1,
    tech: ["Switchgear", "Power management", "MV/LV distribution"], ownership: "Public", region: "Global",
    metric: "Data center electrification portfolio",
    deals: ["VoltaGrid partnership for DC power infrastructure"],
    moat: "Full electrical distribution stack.", note: "Transformers/switchgear are supply-constrained." },
  { name: "Schneider Electric", ticker: "SU.PA", segment: "Electrical Equipment", tier: 1,
    tech: ["UPS", "Switchgear", "DCIM", "Cooling"], ownership: "Public", region: "Global",
    metric: "Leading DC critical-power vendor", deals: [],
    moat: "End-to-end DC electrical + EcoStruxure software.", note: "" },
  { name: "Eaton", ticker: "ETN", segment: "Electrical Equipment", tier: 1,
    tech: ["Switchgear", "UPS", "Busway"], ownership: "Public", region: "Global",
    metric: "Strong DC electrical backlog", deals: [],
    moat: "Electrical distribution + power management.", note: "" },
  { name: "Vertiv", ticker: "VRT", segment: "Electrical Equipment", tier: 1,
    tech: ["UPS", "Power distribution", "Liquid cooling"], ownership: "Public", region: "Global",
    metric: "Critical digital infrastructure leader",
    deals: ["Caterpillar agreement (power integration)"],
    moat: "Power + thermal for high-density AI racks.", note: "" },
  { name: "Hitachi Energy", ticker: "Sub of Hitachi", segment: "Electrical Equipment", tier: 1,
    tech: ["Transformers", "Grid", "HVDC"], ownership: "Public (parent)", region: "Global",
    metric: "Transformer capacity (supply-constrained)", deals: [],
    moat: "Grid + transformer leadership amid shortage.", note: "" },

  // EPC / Development
  { name: "Bechtel", ticker: "Private", segment: "EPC/Dev", tier: 3,
    tech: ["EPC", "Nuclear", "Gas"], ownership: "Private", region: "Global",
    metric: "Mega-project EPC", deals: [],
    moat: "Schedule certainty on complex builds.", note: "" },
  { name: "Quanta Services", ticker: "PWR", segment: "EPC/Dev", tier: 2,
    tech: ["Transmission", "Substation", "EPC"], ownership: "Public", region: "US",
    metric: "Largest US T&D contractor", deals: [],
    moat: "Skilled-labor scale for grid + interconnection.", note: "Labor is a key bottleneck." },
  { name: "Burns & McDonnell", ticker: "Private", segment: "EPC/Dev", tier: 2,
    tech: ["EPC", "Substation", "Power"], ownership: "Private (ESOP)", region: "US",
    metric: "Power + DC engineering", deals: [],
    moat: "Integrated engineering for energization.", note: "" },
  { name: "Fluor", ticker: "FLR", segment: "EPC/Dev", tier: 3,
    tech: ["EPC", "NuScale stake"], ownership: "Public", region: "Global",
    metric: "EPC + SMR exposure (NuScale)", deals: [],
    moat: "EPC scale + SMR equity.", note: "" },

  // Capital
  { name: "Blackstone", ticker: "BX", segment: "Capital", tier: 2,
    tech: ["Infrastructure capital"], ownership: "Public", region: "Global",
    metric: "Major DC + power investor",
    deals: ["VoltaGrid — $1B equity (with Halliburton)"],
    moat: "Scale capital for DC + energy infrastructure.", note: "" },
  { name: "Brookfield", ticker: "BN", segment: "Capital", tier: 2,
    tech: ["Infrastructure + renewables"], ownership: "Public", region: "Global",
    metric: "Renewable + nuclear (Westinghouse) owner",
    deals: ["Bloom Energy — $5B AI-factory partnership", "Westinghouse co-owner"],
    moat: "Owns generation assets + capital.", note: "" },
  { name: "KKR", ticker: "KKR", segment: "Capital", tier: 2,
    tech: ["Infrastructure capital"], ownership: "Public", region: "Global",
    metric: "DC + power infra investments", deals: [],
    moat: "Large infra funds.", note: "" },

  // Fuel / Midstream
  { name: "Chevron", ticker: "CVX", segment: "Fuel/Midstream", tier: 2,
    tech: ["Natural gas", "Co-located power"], ownership: "Public", region: "US",
    metric: "Rebranding as a power-solutions provider",
    deals: ["Microsoft + Engine No.1 — West Texas gas+DC campus (~2,500 MW, ~$7B)"],
    moat: "Upstream gas + power generation integration (Permian).", note: "" },
  { name: "Williams Companies", ticker: "WMB", segment: "Fuel/Midstream", tier: 2,
    tech: ["Gas midstream/pipeline"], ownership: "Public", region: "US",
    metric: "Major US gas pipelines", deals: [],
    moat: "Pipeline capacity to power-hungry regions.", note: "Pipeline capacity is a constraint." },
  { name: "EQT", ticker: "EQT", segment: "Fuel/Midstream", tier: 2,
    tech: ["Natural gas producer"], ownership: "Public", region: "US",
    metric: "Largest US gas producer", deals: [],
    moat: "Low-cost Appalachian gas supply.", note: "" },
  { name: "Halliburton", ticker: "HAL", segment: "Fuel/Midstream", tier: 2,
    tech: ["Distributed power services"], ownership: "Public", region: "Global",
    metric: "Energy services + global footprint",
    deals: ["VoltaGrid JV — distributed DC power (Middle East/global), 400 MW"],
    moat: "Global operations + regulatory expertise for energization.", note: "" },
];

// ---------------------------------------------------------------------------
// Benchmark deals
// ---------------------------------------------------------------------------
const DEALS = [
  { buyer: "Oracle", supplier: "Bloom Energy", tech: "Fuel cell", mw: 2800, model: "BTM", year: "2026", status: "Contracted (1.2 GW deploying)", note: "55-day delivery record" },
  { buyer: "Brookfield", supplier: "Bloom Energy", tech: "Fuel cell", mw: null, model: "BTM", year: "2026", status: "Partnership ($5B)", note: "AI-factory model" },
  { buyer: "CoreWeave", supplier: "Bloom Energy", tech: "Fuel cell", mw: 850, model: "BTM", year: "2025", status: "Operating/ramping", note: "Largest operational BTM fuel-cell fleet" },
  { buyer: "Nebius", supplier: "Bloom Energy", tech: "Fuel cell", mw: 250, model: "BTM", year: "2025", status: "Contracted ($2.6B/10yr)", note: "328 MW installed" },
  { buyer: "Data centers (Eastern Hemisphere)", supplier: "VoltaGrid + Halliburton", tech: "Gas microgrid", mw: 400, model: "BTM", year: "2028", status: "Manufacturing secured", note: "Middle East first" },
  { buyer: "VoltaGrid", supplier: "INNIO Jenbacher", tech: "Gas engine", mw: 1500, model: "BTM", year: "2025", status: "Ordered", note: "Behind-the-meter engines" },
  { buyer: "Microsoft + Engine No.1", supplier: "Chevron", tech: "Gas (co-located)", mw: 2500, model: "BTM", year: "2025", status: "Exclusive negotiation (~$7B)", note: "West Texas Permian gas" },
  { buyer: "Microsoft", supplier: "Constellation", tech: "Nuclear restart", mw: 835, model: "FTM", year: "2027", status: "Contracted", note: "Three Mile Island / Crane restart" },
  { buyer: "Amazon (AWS)", supplier: "Talen Energy", tech: "Nuclear (existing)", mw: 1920, model: "FTM", year: "to 2042", status: "17-yr PPA", note: "Susquehanna; FERC moved BTM→FTM" },
  { buyer: "Amazon", supplier: "X-energy", tech: "SMR", mw: 960, model: "PPA/dev", year: "2030+", status: "Development ($500M+)", note: "Up to 12× Xe-100" },
  { buyer: "Google", supplier: "Kairos Power", tech: "SMR", mw: 500, model: "PPA", year: "2030", status: "Fleet agreement", note: "First corporate SMR fleet; 50 MW initial" },
  { buyer: "Google", supplier: "NextEra", tech: "Nuclear restart", mw: 601, model: "Study", year: "2028+", status: "Restart study", note: "Duane Arnold" },
  { buyer: "Meta", supplier: "Constellation", tech: "Nuclear (existing)", mw: 1100, model: "PPA", year: "to 2047", status: "20-yr PPA", note: "Clinton, IL + uprate" },
  { buyer: "Meta", supplier: "Vistra", tech: "Nuclear (existing)", mw: 2176, model: "PPA", year: "Active", status: "20-yr PPAs", note: "Perry, Davis-Besse, Beaver Valley + uprates" },
  { buyer: "Meta", supplier: "TerraPower", tech: "SMR", mw: 690, model: "Funding/rights", year: "2032+", status: "Funding + rights to 2.1 GW", note: "Natrium" },
  { buyer: "Meta", supplier: "Oklo", tech: "SMR", mw: 1200, model: "PPA", year: "2030+", status: "Up to 1.2 GW", note: "Pike County, Ohio" },
  { buyer: "Equinix", supplier: "Oklo / Radiant / Bloom", tech: "Mixed (SMR/micro/fuel cell)", mw: 500, model: "Mixed", year: "2027–2030+", status: "Contracted/LOI", note: "Diversified strategy across 19 sites" },
];

// ---------------------------------------------------------------------------
// Regions
// ---------------------------------------------------------------------------
const REGIONS = [
  { name: "PJM (US Mid-Atlantic)", hub: "Northern Virginia — 'Data Center Alley'",
    profile: "Nuclear-heavy, tight capacity, high prices, long queues.", model: "Grid + nuclear PPA",
    tags: ["High demand", "Nuclear", "Constrained"] },
  { name: "ERCOT (Texas)", hub: "Dallas, San Antonio, West Texas",
    profile: "Fast permitting, abundant Permian gas, strong co-location appetite.", model: "BTM gas / co-located",
    tags: ["Fast permitting", "Gas", "BTM-friendly"] },
  { name: "US Southeast", hub: "Georgia (Atlanta), TVA region",
    profile: "Load growth, new gas + nuclear interest (Georgia Power, TVA, Entergy).", model: "Regulated utility + gas",
    tags: ["Growth", "Nuclear interest"] },
  { name: "US West", hub: "Phoenix, Nevada",
    profile: "Solar + storage rich; water constraints (NV Energy, APS).", model: "Solar+storage",
    tags: ["Renewables", "Water-constrained"] },
  { name: "Middle East", hub: "UAE, Saudi Arabia",
    profile: "Sovereign-backed AI build-outs; abundant gas; speed + scale ambition.", model: "Turnkey gas microgrid",
    tags: ["Fast-growing", "Sovereign capital", "Gas"] },
  { name: "Europe (EMEA)", hub: "Ireland, Nordics, Germany, Netherlands",
    profile: "Grid constraints + moratoria; Nordics offer cheap clean power.", model: "Grid + renewables",
    tags: ["Grid-constrained", "Clean power"] },
  { name: "APAC", hub: "Japan, Korea, Singapore, India, Malaysia (Johor)",
    profile: "Singapore easing moratorium; Johor surging; separate China supply chain.", model: "Mixed",
    tags: ["Emerging", "Diverse"] },
];

// ---------------------------------------------------------------------------
// Bottlenecks
// ---------------------------------------------------------------------------
const BOTTLENECKS = [
  { name: "Heavy-duty gas turbines", severity: "Critical",
    detail: "3 OEMs control >70% of capacity; sold out to ~2028, new slots 2029–2030; 3–5 yr lead times. >$400B of planned gas plants at risk.",
    controllers: ["GE Vernova", "Siemens Energy", "Mitsubishi Heavy Industries"] },
  { name: "Grid interconnection", severity: "Critical",
    detail: ">4-year waits in primary US markets; transmission siting/permitting. Driver of the shift to behind-the-meter.",
    controllers: ["Utilities", "RTOs (PJM/ERCOT)"] },
  { name: "Transformers & switchgear", severity: "High",
    detail: "Multi-year lead times constrain both grid and BTM builds.",
    controllers: ["Hitachi Energy", "ABB", "Eaton", "Schneider"] },
  { name: "Skilled labor & EPC", severity: "High",
    detail: "Electricians, gas-plant builders, nuclear-qualified trades in short supply.",
    controllers: ["Quanta", "Bechtel", "Burns & McDonnell"] },
  { name: "Fuel logistics / pipelines", severity: "Medium",
    detail: "Gas pipeline capacity is basin-specific (e.g., Permian/Texas); midstream relationships matter.",
    controllers: ["Williams", "Energy Transfer", "Kinder Morgan"] },
  { name: "Nuclear licensing & SMR supply chain", severity: "Medium-Long",
    detail: "NRC timelines; immature SMR supply chains; <2 GW likely online before ~2033.",
    controllers: ["NRC", "TerraPower", "Oklo", "X-energy"] },
];
