/*
 * Data Center Power & Energization — dataset
 * As-of: May 2026. Figures are point-in-time estimates drawn from IEA, JLL,
 * company disclosures and industry/press reporting. Verify before decisions.
 */

// ---------------------------------------------------------------------------
// Demand scenarios (IEA, global data center electricity, TWh)
// ---------------------------------------------------------------------------
const DEMAND = {
  years: [2024, 2025, 2030, 2035],
  scenarios: {
    "Base Case":      [415, 485, 945, 1193],
    "Lift-Off":       [415, 485, 1008, 1637],
    "High Efficiency":[415, 485, 868, 1013],
    "Headwinds":      [415, 485, 833, 942],
  },
  // Capacity (GW) installed base, JLL
  capacity: { years: [2025, 2030], gw: [103, 200] },
  // AI share of data center workloads (%)
  aiShare: { years: [2025, 2027, 2030], pct: [25, 45, 50] },
  notes: [
    "2024 ≈ 415 TWh (~1.5% of global electricity); grew ~17% to ~485 TWh in 2025.",
    "Base Case roughly doubles to ~945 TWh by 2030 (~3% of global electricity), ~15%/yr growth.",
    "Capacity ~doubles to ~200 GW by 2030 (~14% CAGR), ~97–100 GW added.",
    "AI ≈ 25% of workloads in 2025 → ~50% by 2030; inference overtakes training ~2027.",
    "Interconnection waits exceed ~4 years in primary US markets — the binding constraint.",
  ],
};

const KPIS = [
  { label: "Global DC electricity, 2025", value: "~485 TWh", sub: "+17% YoY (IEA)" },
  { label: "Projected 2030 (Base Case)", value: "~945 TWh", sub: "~3% of global power" },
  { label: "Capacity by 2030", value: "~200 GW", sub: "~14% CAGR, ~2x" },
  { label: "AI share of workloads 2030", value: "~50%", sub: "inference-led from 2027" },
  { label: "Gas-turbine backlog", value: "3–5 yrs", sub: "sold out to ~2028" },
  { label: "Grid interconnection wait", value: ">4 yrs", sub: "primary US markets" },
];

// ---------------------------------------------------------------------------
// Technology stack (sorted by time-to-power tier)
// ---------------------------------------------------------------------------
const TECHNOLOGIES = [
  { name: "Fuel cells (SOFC)", tier: 1, ttp: "≈55–90 days", capex: "$3,000–4,000/kW",
    emissions: "Very low local (no combustion)", readiness: "Commercial",
    players: ["Bloom Energy"],
    note: "Fastest viable energization where air permitting is the binding constraint." },
  { name: "Linear generators (multi-fuel)", tier: 1, ttp: "Months", capex: "Moderate",
    emissions: "Near-zero NOx, no after-treatment", readiness: "Early commercial",
    players: ["Mainspring Energy"],
    note: "Gas/biogas/propane/hydrogen; fast start/ramp; factory-built modular." },
  { name: "Rental / mobile gensets", tier: 1, ttp: "Weeks", capex: "Low (opex-heavy)",
    emissions: "High (diesel)", readiness: "Commercial",
    players: ["Aggreko", "Cat Rental"],
    note: "Bridge power while permanent assets are built." },
  { name: "Reciprocating gas engines", tier: 2, ttp: "≈18 months", capex: "Lower upfront",
    emissions: "Moderate", readiness: "Commercial",
    players: ["Caterpillar", "INNIO Jenbacher", "Wärtsilä", "Rolls-Royce (mtu)", "Cummins"],
    note: "Baseload + backup; modular; shorter lead than turbines." },
  { name: "Aeroderivative gas turbines", tier: 2, ttp: "1–2 years", capex: "Moderate",
    emissions: "Moderate", readiness: "Commercial",
    players: ["Solar Turbines (Caterpillar)", "GE Vernova (LM)", "Siemens Energy"],
    note: "Faster, skid-mounted vs heavy-duty." },
  { name: "Solar + wind + storage", tier: 2, ttp: "1–3 years", capex: "Falling",
    emissions: "Zero (variable)", readiness: "Commercial",
    players: ["NextEra", "Amazon (self-build)"],
    note: "Needs firming; pairs with BESS." },
  { name: "Turnkey gas microgrid", tier: 2, ttp: "12–24 months", capex: "Power-agreement (PaaS)",
    emissions: "Lower than diesel", readiness: "Commercial",
    players: ["VoltaGrid", "ProEnergy", "Mainspring Energy"],
    note: "Single power agreement: fuel + generation + O&M." },
  { name: "Heavy-duty gas turbine (H-class)", tier: 3, ttp: "3–5 years", capex: "High",
    emissions: "Moderate (CCGT efficient)", readiness: "Commercial (sold out)",
    players: ["GE Vernova", "Siemens Energy", "Mitsubishi Heavy Industries"],
    note: ">600 MW, >65% CCGT efficiency; order books full to ~2028–2030." },
  { name: "Nuclear — existing / restart / uprate", tier: 3, ttp: "1–4 years (restart)", capex: "High",
    emissions: "Zero", readiness: "Commercial",
    players: ["Constellation", "Vistra", "Talen", "NextEra", "Dominion"],
    note: "Fastest firm carbon-free route via restarts, uprates, life extension." },
  { name: "Nuclear — SMR / microreactor", tier: 3, ttp: "2030+", capex: "High (FOAK)",
    emissions: "Zero", readiness: "Pre-commercial",
    players: ["TerraPower", "Oklo", "X-energy", "Kairos Power", "NuScale", "Westinghouse", "Radiant"],
    note: "Long-term prize; <2 GW likely online before ~2033." },
  { name: "Battery storage (BESS)", tier: 2, ttp: "Months–1 year", capex: "Falling",
    emissions: "Zero (operation)", readiness: "Commercial",
    players: ["Tesla", "Fluence", "Multiple"],
    note: "~20–25 GW paired with DCs by 2030; smooths AI power swings." },
];

const TIER_LABELS = {
  1: "Tier 1 · Immediate (months)",
  2: "Tier 2 · Medium (1–3 yrs)",
  3: "Tier 3 · Long horizon (3+ yrs / 2030+)",
};

// ---------------------------------------------------------------------------
// Companies
// segment ∈ Utility | IPP | Turbine OEM | Engine/Distributed | BTM Integrator
//          | Nuclear/SMR | Electrical Equipment | EPC/Dev | Capital | Fuel/Midstream
// ---------------------------------------------------------------------------
const COMPANIES = [
  // IPPs
  { name: "Constellation Energy", ticker: "CEG", segment: "IPP", tier: 3,
    tech: ["Nuclear (existing/restart)"], ownership: "Public", region: "US",
    metric: "~60 GW fleet (largest US nuclear)",
    deals: ["Microsoft TMI/Crane restart (835 MW, ~2027)", "Meta Clinton (1.1 GW, 20-yr)"],
    moat: "Largest US nuclear fleet; restart optionality; firm carbon-free.",
    note: "Most leveraged to firm-power scarcity." },
  { name: "Vistra", ticker: "VST", segment: "IPP", tier: 3,
    tech: ["Nuclear", "Gas"], ownership: "Public", region: "US",
    metric: "~45 GW fleet",
    deals: ["Meta — Perry, Davis-Besse, Beaver Valley (~2.2 GW + uprates)"],
    moat: "Nuclear + gas fleet; capacity revenue locked through 2028.",
    note: "" },
  { name: "Talen Energy", ticker: "TLN", segment: "IPP", tier: 3,
    tech: ["Nuclear"], ownership: "Public", region: "US",
    metric: "~13 GW fleet",
    deals: ["AWS — Susquehanna (~1.92 GW, 17-yr PPA to 2042)"],
    moat: "Co-located nuclear adjacency to PJM data center demand.",
    note: "Deal shifted BTM → front-of-meter after FERC concerns." },
  { name: "NRG Energy", ticker: "NRG", segment: "IPP", tier: 2,
    tech: ["Gas"], ownership: "Public", region: "US",
    metric: "~28 GW fleet",
    deals: [], moat: "Merchant gas capacity in tight markets.", note: "" },
  { name: "NextEra Energy", ticker: "NEE", segment: "IPP", tier: 2,
    tech: ["Renewables", "Nuclear"], ownership: "Public", region: "US",
    metric: "Largest US renewables operator",
    deals: ["Google — Duane Arnold restart study (~601 MW)"],
    moat: "Scale in solar+storage + nuclear restarts.", note: "" },

  // Turbine OEMs
  { name: "GE Vernova", ticker: "GEV", segment: "Turbine OEM", tier: 3,
    tech: ["Heavy-duty gas turbine", "Aeroderivative"], ownership: "Public", region: "Global",
    metric: "~80 GW orderbook; powers ~50% of US electrons",
    deals: ["~20–33% of slot reservations tied to AI/hyperscalers"],
    moat: "One of three large-turbine makers; controls scarce slots.",
    note: "Sold out to ~2028; capacity additions mostly post-2028." },
  { name: "Siemens Energy", ticker: "ENR", segment: "Turbine OEM", tier: 3,
    tech: ["Heavy-duty gas turbine", "Grid"], ownership: "Public", region: "Global",
    metric: "Record backlog ~€146B",
    deals: ["Quoting 2029–2030 delivery slots"],
    moat: "Big-three turbine maker + grid equipment.", note: "" },
  { name: "Mitsubishi Heavy Industries", ticker: "7011.T", segment: "Turbine OEM", tier: 3,
    tech: ["Heavy-duty gas turbine"], ownership: "Public", region: "Global",
    metric: "Energy bookings +45% YoY",
    deals: ["Most slots booked 2027–2028; doubling capacity"],
    moat: "Big-three turbine maker.", note: "" },

  // Engine / distributed OEMs
  { name: "Caterpillar", ticker: "CAT", segment: "Engine/Distributed", tier: 2,
    tech: ["Recip gas engine", "Aeroderivative (Solar Turbines)"], ownership: "Public", region: "Global",
    metric: "Solar Turbines expanding capacity ~2.5x",
    deals: ["Agreements with Vertiv and Joule Capital Partners"],
    moat: "Broad engine + turbine portfolio; service network.", note: "" },
  { name: "Cummins", ticker: "CMI", segment: "Engine/Distributed", tier: 2,
    tech: ["Recip gas/diesel engine", "Backup gensets"], ownership: "Public", region: "Global",
    metric: "Major genset supplier", deals: [],
    moat: "Backup/prime power gensets at scale.", note: "" },
  { name: "INNIO Jenbacher", ticker: "Private (Advent)", segment: "Engine/Distributed", tier: 2,
    tech: ["Recip gas engine"], ownership: "Private", region: "Global",
    metric: "Mega-orders for data center power",
    deals: ["VoltaGrid — 1.5 GW behind-the-meter engine order"],
    moat: "High-efficiency gas engines; hydrogen-capable.", note: "" },
  { name: "Wärtsilä", ticker: "WRT1V.HE", segment: "Engine/Distributed", tier: 2,
    tech: ["Recip gas engine"], ownership: "Public", region: "Global",
    metric: "Energy division +29% sales (Q4 2025)", deals: [],
    moat: "Flexible balancing engines + storage.", note: "" },
  { name: "Rolls-Royce Power Systems (mtu)", ticker: "RR.L", segment: "Engine/Distributed", tier: 2,
    tech: ["Recip gas engine", "Backup"], ownership: "Public", region: "Global",
    metric: "DC power gen products +~50%", deals: [],
    moat: "mtu engines; data center backup pedigree.", note: "" },

  // BTM Integrators / onsite power-as-a-service
  { name: "Bloom Energy", ticker: "BE", segment: "BTM Integrator", tier: 1,
    tech: ["Fuel cells (SOFC)"], ownership: "Public", region: "US/Global",
    metric: "55-day delivery record; stock +150% YTD",
    deals: ["Oracle (up to 2.8 GW MSA; 1.2 GW deploying)", "Brookfield ($5B AI-factory partnership)",
            "CoreWeave (~850 MW operating)", "Nebius (250 MW / $2.6B over decade)"],
    moat: "Fastest energization; sidesteps combustion permitting.",
    note: "Leading near-term onsite technology." },
  { name: "Mainspring Energy", ticker: "Private", segment: "BTM Integrator", tier: 1,
    tech: ["Linear generators"], ownership: "Private", region: "US",
    metric: "Factory-built, multi-fuel modular",
    deals: [], moat: "Near-zero NOx, no after-treatment; fuel-flexible.",
    note: "Deploys in months; islanding capable." },
  { name: "VoltaGrid", ticker: "Private", segment: "BTM Integrator", tier: 2,
    tech: ["Turnkey gas microgrid", "Hybrid + storage"], ownership: "Private", region: "US/Global",
    metric: "$5B financing; $1B equity (Blackstone+Halliburton)",
    deals: ["Halliburton JV — 400 MW (2028, Eastern Hemisphere)", "INNIO — 1.5 GW engines",
            "ABB partnership", "Oracle collaboration"],
    moat: "Turnkey power agreement (power+fuel+logistics); global reach via Halliburton.",
    note: "Targeting Middle East / Eastern Hemisphere first." },
  { name: "ProEnergy", ticker: "Private", segment: "BTM Integrator", tier: 2,
    tech: ["Aeroderivative", "Modular plant"], ownership: "Private", region: "US",
    metric: "Fast-track modular gas plants",
    deals: [], moat: "Repowered aero turbines for fast deployment.", note: "" },

  // Nuclear / SMR developers
  { name: "TerraPower", ticker: "Private (Gates)", segment: "Nuclear/SMR", tier: 3,
    tech: ["SMR (Natrium)"], ownership: "Private", region: "US",
    metric: "First NRC construction permit (2026); ~345 MW Natrium",
    deals: ["Meta — 2 Natrium units (~690 MWe) + rights to ~2.1 GW by 2035"],
    moat: "Sodium-cooled + molten-salt storage; Gates-backed.",
    note: "Wyoming project targeting ops ~2031–2032." },
  { name: "Oklo", ticker: "OKLO", segment: "Nuclear/SMR", tier: 3,
    tech: ["Microreactor (Aurora)"], ownership: "Public", region: "US",
    metric: "Build-own-operate model",
    deals: ["Meta (~0.75–1.2 GW, Ohio)", "Switch framework", "Equinix (500 MW)"],
    moat: "Sell power not reactors; early DC relationships.",
    note: "Commercial deployment early 2030s." },
  { name: "X-energy", ticker: "Private", segment: "Nuclear/SMR", tier: 3,
    tech: ["SMR (Xe-100)"], ownership: "Private", region: "US",
    metric: "Up to 12× Xe-100 with Amazon",
    deals: ["Amazon — ~$700M / $500M round; SMR development"],
    moat: "HTGR pebble-bed; Amazon-backed.", note: "" },
  { name: "Kairos Power", ticker: "Private", segment: "Nuclear/SMR", tier: 3,
    tech: ["SMR (KP-FHR)"], ownership: "Private", region: "US",
    metric: "NRC construction permit (Hermes, 2023)",
    deals: ["Google — first corporate SMR fleet (50 → ~500 MW by 2035)"],
    moat: "Fluoride-salt-cooled high-temp reactor; Google partner.", note: "" },
  { name: "NuScale Power", ticker: "SMR", segment: "Nuclear/SMR", tier: 3,
    tech: ["SMR"], ownership: "Public", region: "US/Global",
    metric: "Only NRC-approved SMR design",
    deals: ["Romania deployment (first module ~2033)"],
    moat: "Design certification lead.", note: "" },
  { name: "Westinghouse", ticker: "Private (Cameco/Brookfield)", segment: "Nuclear/SMR", tier: 3,
    tech: ["AP300 SMR", "eVinci microreactor", "AP1000"], ownership: "Private", region: "Global",
    metric: "Established reactor vendor",
    deals: [], moat: "Large installed base + new SMR designs.", note: "" },
  { name: "Radiant", ticker: "Private", segment: "Nuclear/SMR", tier: 3,
    tech: ["Microreactor (Kaleidos)"], ownership: "Private", region: "US",
    metric: "Portable microreactor",
    deals: ["Equinix — preorder (20× Kaleidos units)"],
    moat: "Transportable microreactor for distributed sites.", note: "" },
  { name: "Dominion Energy", ticker: "D", segment: "Nuclear/SMR", tier: 3,
    tech: ["Nuclear", "Utility"], ownership: "Public", region: "US",
    metric: "Serves Data Center Alley (Virginia)",
    deals: ["Amazon — Lake Anna SMR study", "Meta — multiple"],
    moat: "Owns the grid in the largest US DC market.", note: "" },

  // Electrical equipment (inside-the-fence)
  { name: "ABB", ticker: "ABBN.SW", segment: "Electrical Equipment", tier: 1,
    tech: ["Switchgear", "Power management", "MV/LV distribution"], ownership: "Public", region: "Global",
    metric: "Data center electrification portfolio",
    deals: ["VoltaGrid partnership for DC power infrastructure"],
    moat: "Full electrical distribution stack.", note: "Transformers/switchgear are supply-constrained." },
  { name: "Schneider Electric", ticker: "SU.PA", segment: "Electrical Equipment", tier: 1,
    tech: ["UPS", "Switchgear", "DCIM", "Cooling"], ownership: "Public", region: "Global",
    metric: "Leading DC critical-power vendor", deals: [],
    moat: "End-to-end DC electrical + EcoStruxure software.", note: "" },
  { name: "Eaton", ticker: "ETN", segment: "Electrical Equipment", tier: 1,
    tech: ["Switchgear", "UPS", "Busway"], ownership: "Public", region: "Global",
    metric: "Strong DC electrical backlog", deals: [],
    moat: "Electrical distribution + power management.", note: "" },
  { name: "Vertiv", ticker: "VRT", segment: "Electrical Equipment", tier: 1,
    tech: ["UPS", "Power distribution", "Liquid cooling"], ownership: "Public", region: "Global",
    metric: "Critical digital infrastructure leader",
    deals: ["Caterpillar agreement (power integration)"],
    moat: "Power + thermal for high-density AI racks.", note: "" },
  { name: "Hitachi Energy", ticker: "Sub of Hitachi", segment: "Electrical Equipment", tier: 1,
    tech: ["Transformers", "Grid", "HVDC"], ownership: "Public (parent)", region: "Global",
    metric: "Transformer capacity (supply-constrained)", deals: [],
    moat: "Grid + transformer leadership amid shortage.", note: "" },

  // EPC / Development
  { name: "Bechtel", ticker: "Private", segment: "EPC/Dev", tier: 3,
    tech: ["EPC", "Nuclear", "Gas"], ownership: "Private", region: "Global",
    metric: "Mega-project EPC", deals: [],
    moat: "Schedule certainty on complex builds.", note: "" },
  { name: "Quanta Services", ticker: "PWR", segment: "EPC/Dev", tier: 2,
    tech: ["Transmission", "Substation", "EPC"], ownership: "Public", region: "US",
    metric: "Largest US T&D contractor", deals: [],
    moat: "Skilled-labor scale for grid + interconnection.", note: "Labor is a key bottleneck." },
  { name: "Burns & McDonnell", ticker: "Private", segment: "EPC/Dev", tier: 2,
    tech: ["EPC", "Substation", "Power"], ownership: "Private (ESOP)", region: "US",
    metric: "Power + DC engineering", deals: [],
    moat: "Integrated engineering for energization.", note: "" },
  { name: "Fluor", ticker: "FLR", segment: "EPC/Dev", tier: 3,
    tech: ["EPC", "NuScale stake"], ownership: "Public", region: "Global",
    metric: "EPC + SMR exposure (NuScale)", deals: [],
    moat: "EPC scale + SMR equity.", note: "" },

  // Capital
  { name: "Blackstone", ticker: "BX", segment: "Capital", tier: 2,
    tech: ["Infrastructure capital"], ownership: "Public", region: "Global",
    metric: "Major DC + power investor",
    deals: ["VoltaGrid — $1B equity (with Halliburton)"],
    moat: "Scale capital for DC + energy infrastructure.", note: "" },
  { name: "Brookfield", ticker: "BN", segment: "Capital", tier: 2,
    tech: ["Infrastructure + renewables"], ownership: "Public", region: "Global",
    metric: "Renewable + nuclear (Westinghouse) owner",
    deals: ["Bloom Energy — $5B AI-factory partnership", "Westinghouse co-owner"],
    moat: "Owns generation assets + capital.", note: "" },
  { name: "KKR", ticker: "KKR", segment: "Capital", tier: 2,
    tech: ["Infrastructure capital"], ownership: "Public", region: "Global",
    metric: "DC + power infra investments", deals: [],
    moat: "Large infra funds.", note: "" },

  // Fuel / Midstream
  { name: "Chevron", ticker: "CVX", segment: "Fuel/Midstream", tier: 2,
    tech: ["Natural gas", "Co-located power"], ownership: "Public", region: "US",
    metric: "Rebranding as a power-solutions provider",
    deals: ["Microsoft + Engine No.1 — West Texas gas+DC campus (~2,500 MW, ~$7B)"],
    moat: "Upstream gas + power generation integration (Permian).", note: "" },
  { name: "Williams Companies", ticker: "WMB", segment: "Fuel/Midstream", tier: 2,
    tech: ["Gas midstream/pipeline"], ownership: "Public", region: "US",
    metric: "Major US gas pipelines", deals: [],
    moat: "Pipeline capacity to power-hungry regions.", note: "Pipeline capacity is a constraint." },
  { name: "EQT", ticker: "EQT", segment: "Fuel/Midstream", tier: 2,
    tech: ["Natural gas producer"], ownership: "Public", region: "US",
    metric: "Largest US gas producer", deals: [],
    moat: "Low-cost Appalachian gas supply.", note: "" },
  { name: "Halliburton", ticker: "HAL", segment: "Fuel/Midstream", tier: 2,
    tech: ["Distributed power services"], ownership: "Public", region: "Global",
    metric: "Energy services + global footprint",
    deals: ["VoltaGrid JV — distributed DC power (Middle East/global), 400 MW"],
    moat: "Global operations + regulatory expertise for energization.", note: "" },
];

// ---------------------------------------------------------------------------
// Benchmark deals
// ---------------------------------------------------------------------------
const DEALS = [
  { buyer: "Oracle", supplier: "Bloom Energy", tech: "Fuel cell", mw: 2800, model: "BTM", year: "2026", status: "Contracted (1.2 GW deploying)", note: "55-day delivery record" },
  { buyer: "Brookfield", supplier: "Bloom Energy", tech: "Fuel cell", mw: null, model: "BTM", year: "2026", status: "Partnership ($5B)", note: "AI-factory model" },
  { buyer: "CoreWeave", supplier: "Bloom Energy", tech: "Fuel cell", mw: 850, model: "BTM", year: "2025", status: "Operating/ramping", note: "Largest operational BTM fuel-cell fleet" },
  { buyer: "Nebius", supplier: "Bloom Energy", tech: "Fuel cell", mw: 250, model: "BTM", year: "2025", status: "Contracted ($2.6B/10yr)", note: "328 MW installed" },
  { buyer: "Data centers (Eastern Hemisphere)", supplier: "VoltaGrid + Halliburton", tech: "Gas microgrid", mw: 400, model: "BTM", year: "2028", status: "Manufacturing secured", note: "Middle East first" },
  { buyer: "VoltaGrid", supplier: "INNIO Jenbacher", tech: "Gas engine", mw: 1500, model: "BTM", year: "2025", status: "Ordered", note: "Behind-the-meter engines" },
  { buyer: "Microsoft + Engine No.1", supplier: "Chevron", tech: "Gas (co-located)", mw: 2500, model: "BTM", year: "2025", status: "Exclusive negotiation (~$7B)", note: "West Texas Permian gas" },
  { buyer: "Microsoft", supplier: "Constellation", tech: "Nuclear restart", mw: 835, model: "FTM", year: "2027", status: "Contracted", note: "Three Mile Island / Crane restart" },
  { buyer: "Amazon (AWS)", supplier: "Talen Energy", tech: "Nuclear (existing)", mw: 1920, model: "FTM", year: "to 2042", status: "17-yr PPA", note: "Susquehanna; FERC moved BTM→FTM" },
  { buyer: "Amazon", supplier: "X-energy", tech: "SMR", mw: 960, model: "PPA/dev", year: "2030+", status: "Development ($500M+)", note: "Up to 12× Xe-100" },
  { buyer: "Google", supplier: "Kairos Power", tech: "SMR", mw: 500, model: "PPA", year: "2030", status: "Fleet agreement", note: "First corporate SMR fleet; 50 MW initial" },
  { buyer: "Google", supplier: "NextEra", tech: "Nuclear restart", mw: 601, model: "Study", year: "2028+", status: "Restart study", note: "Duane Arnold" },
  { buyer: "Meta", supplier: "Constellation", tech: "Nuclear (existing)", mw: 1100, model: "PPA", year: "to 2047", status: "20-yr PPA", note: "Clinton, IL + uprate" },
  { buyer: "Meta", supplier: "Vistra", tech: "Nuclear (existing)", mw: 2176, model: "PPA", year: "Active", status: "20-yr PPAs", note: "Perry, Davis-Besse, Beaver Valley + uprates" },
  { buyer: "Meta", supplier: "TerraPower", tech: "SMR", mw: 690, model: "Funding/rights", year: "2032+", status: "Funding + rights to 2.1 GW", note: "Natrium" },
  { buyer: "Meta", supplier: "Oklo", tech: "SMR", mw: 1200, model: "PPA", year: "2030+", status: "Up to 1.2 GW", note: "Pike County, Ohio" },
  { buyer: "Equinix", supplier: "Oklo / Radiant / Bloom", tech: "Mixed (SMR/micro/fuel cell)", mw: 500, model: "Mixed", year: "2027–2030+", status: "Contracted/LOI", note: "Diversified strategy across 19 sites" },
];

// ---------------------------------------------------------------------------
// Regions
// ---------------------------------------------------------------------------
const REGIONS = [
  { name: "PJM (US Mid-Atlantic)", hub: "Northern Virginia — 'Data Center Alley'",
    profile: "Nuclear-heavy, tight capacity, high prices, long queues.", model: "Grid + nuclear PPA",
    tags: ["High demand", "Nuclear", "Constrained"] },
  { name: "ERCOT (Texas)", hub: "Dallas, San Antonio, West Texas",
    profile: "Fast permitting, abundant Permian gas, strong co-location appetite.", model: "BTM gas / co-located",
    tags: ["Fast permitting", "Gas", "BTM-friendly"] },
  { name: "US Southeast", hub: "Georgia (Atlanta), TVA region",
    profile: "Load growth, new gas + nuclear interest (Georgia Power, TVA, Entergy).", model: "Regulated utility + gas",
    tags: ["Growth", "Nuclear interest"] },
  { name: "US West", hub: "Phoenix, Nevada",
    profile: "Solar + storage rich; water constraints (NV Energy, APS).", model: "Solar+storage",
    tags: ["Renewables", "Water-constrained"] },
  { name: "Middle East", hub: "UAE, Saudi Arabia",
    profile: "Sovereign-backed AI build-outs; abundant gas; speed + scale ambition.", model: "Turnkey gas microgrid",
    tags: ["Fast-growing", "Sovereign capital", "Gas"] },
  { name: "Europe (EMEA)", hub: "Ireland, Nordics, Germany, Netherlands",
    profile: "Grid constraints + moratoria; Nordics offer cheap clean power.", model: "Grid + renewables",
    tags: ["Grid-constrained", "Clean power"] },
  { name: "APAC", hub: "Japan, Korea, Singapore, India, Malaysia (Johor)",
    profile: "Singapore easing moratorium; Johor surging; separate China supply chain.", model: "Mixed",
    tags: ["Emerging", "Diverse"] },
];

// ---------------------------------------------------------------------------
// Bottlenecks
// ---------------------------------------------------------------------------
const BOTTLENECKS = [
  { name: "Heavy-duty gas turbines", severity: "Critical",
    detail: "3 OEMs control >70% of capacity; sold out to ~2028, new slots 2029–2030; 3–5 yr lead times. >$400B of planned gas plants at risk.",
    controllers: ["GE Vernova", "Siemens Energy", "Mitsubishi Heavy Industries"] },
  { name: "Grid interconnection", severity: "Critical",
    detail: ">4-year waits in primary US markets; transmission siting/permitting. Driver of the shift to behind-the-meter.",
    controllers: ["Utilities", "RTOs (PJM/ERCOT)"] },
  { name: "Transformers & switchgear", severity: "High",
    detail: "Multi-year lead times constrain both grid and BTM builds.",
    controllers: ["Hitachi Energy", "ABB", "Eaton", "Schneider"] },
  { name: "Skilled labor & EPC", severity: "High",
    detail: "Electricians, gas-plant builders, nuclear-qualified trades in short supply.",
    controllers: ["Quanta", "Bechtel", "Burns & McDonnell"] },
  { name: "Fuel logistics / pipelines", severity: "Medium",
    detail: "Gas pipeline capacity is basin-specific (e.g., Permian/Texas); midstream relationships matter.",
    controllers: ["Williams", "Energy Transfer", "Kinder Morgan"] },
  { name: "Nuclear licensing & SMR supply chain", severity: "Medium-Long",
    detail: "NRC timelines; immature SMR supply chains; <2 GW likely online before ~2033.",
    controllers: ["NRC", "TerraPower", "Oklo", "X-energy"] },
];

// ---------------------------------------------------------------------------
// Product Strategy — from landscape analysis
// ---------------------------------------------------------------------------

const STRATEGY = {
  opportunity: {
    title: "The White Space",
    text: "~97 GW of new data center capacity must be energized by 2030. Hyperscalers (MSFT, AMZN, GOOG, META) have in-house power teams and sign GW-scale deals directly. But the next ~500 colocation operators, AI startups, and enterprise DC owners — each building 10–500 MW — lack the expertise, supplier relationships, and negotiating power to navigate a fragmented, supply-constrained power market where interconnection takes >4 years and turbine slots are sold out to 2028. Nobody is solving the full procurement + orchestration + optimization problem for this mid-market tier.",
  },

  product: {
    name: "PowerPath",
    tagline: "Energization intelligence and procurement platform for data centers",
    oneLiner: "We compress time-to-power for data center operators by combining an AI-driven energization planning engine with pre-negotiated supply access and real-time asset orchestration.",
    layers: [
      { name: "PowerPath Scout", phase: "P1 — Now",
        what: "Energization planning & procurement advisory platform (SaaS + services)",
        detail: "Ingests a site's location, load profile, timeline, and budget. Runs constraint-aware optimization across the full technology stack (fuel cells, engines, aero turbines, solar+storage, grid queue position) and outputs a ranked energization plan with specific supplier recommendations, $/MWh projections, permitting risk scores, and time-to-power estimates. Includes a curated supplier marketplace with pre-negotiated framework agreements.",
        revenue: "Platform SaaS ($5K–25K/mo per site) + procurement success fee (1–3% of equipment/PPA value)",
        icon: "🔍" },
      { name: "PowerPath Control", phase: "P2 — +12 mo",
        what: "Hybrid asset orchestration & energy management system (EMS)",
        detail: "Real-time software layer that sits across multiple BTM generation assets (fuel cells, engines, BESS, solar, grid connection) and optimizes dispatch, fuel purchasing, maintenance scheduling, and grid-services revenue. Solves the problem that a 50 MW campus with Bloom fuel cells + INNIO engines + Tesla BESS + grid backup needs a unified control plane — today they're managed in silos.",
        revenue: "SaaS ($8–40K/mo per site) + performance fee (share of energy cost savings / grid-services revenue)",
        icon: "⚡" },
      { name: "PowerPath Capital", phase: "P3 — +24 mo",
        what: "Energization-as-a-service (EaaS) — own/finance the assets",
        detail: "Graduate from software to owning the BTM generation assets and selling power under long-term power agreements ($/MWh, take-or-pay). Use the Scout data to identify the best sites, the Control software to operate efficiently, and infrastructure capital (Blackstone, Brookfield, KKR-type) to fund. Essentially become a data-center-focused IPP with a software edge.",
        revenue: "Power agreement ($/MWh × contracted MW × utilization) + equipment margin",
        icon: "🏗️" },
    ],
  },

  firstProduct: {
    name: "PowerPath Scout",
    why: [
      "Lowest capital requirement — software + advisory, not hardware",
      "Fastest to market — can launch with a small team of power engineers + a web platform",
      "Builds the proprietary dataset (site plans, supplier pricing, lead times, permitting data) that becomes the moat for P2 and P3",
      "Every engagement is a lead-gen funnel for P2 (sell them the EMS) and P3 (finance their assets)",
      "Directly addresses the #1 pain point: 'I have capital and a site but I can't figure out how to get power in <18 months'",
    ],
    mvp: [
      "Energization planning engine: input site location + MW + timeline → output ranked technology mix, supplier shortlist, $/MWh range, permitting path, time-to-power estimate",
      "Supplier database with real-time slot availability (start with Bloom, INNIO, Caterpillar, Mainspring, VoltaGrid — the Tier 1-2 stack)",
      "Interconnection queue tracker (PJM, ERCOT, MISO, SPP) with estimated wait times per utility/substation",
      "Deal benchmarking: anonymized pricing and terms from the 17+ tracked deals in our dataset, so customers know what 'fair' looks like",
      "Advisory layer: 3–5 senior power engineers who run the platform with the customer and negotiate on their behalf",
    ],
    timeline: "MVP in 4 months → first paying customer in 6 months → 10 customers by month 12",
  },

  icp: {
    title: "Ideal Customer Profile (ICP)",
    primary: {
      segment: "Mid-market colocation & AI-native data center operators",
      size: "Building or expanding 10–500 MW of capacity",
      pain: "Need power in <18 months; don't have an in-house power procurement team; can't get hyperscaler-level supplier access or pricing",
      budget: "Willing to pay $60K–300K/yr for platform + advisory that saves 6–18 months of time-to-power and 10–25% on $/MWh",
      examples: [
        { name: "CoreWeave", why: "AI GPU cloud; scaling fast; already using Bloom fuel cells; needs orchestration across multiple generation sources as they grow beyond 1 GW" },
        { name: "Nebius (Yandex spin-off)", why: "European AI infra; just signed $2.6B Bloom deal; likely needs help planning next sites" },
        { name: "Lambda Labs / Together AI / Cerebras Cloud", why: "AI-native GPU providers; fundraising at scale; need 50–200 MW fast; zero power expertise in-house" },
        { name: "Vantage / QTS / Cyrus One / DataBank / Stack / Prime", why: "Second-tier colo operators building 50–200 MW expansions; strong DC ops teams but thin on power procurement" },
        { name: "Compass / EdgeConneX / Yondr", why: "Global colo operators entering new markets (Middle East, APAC) where power landscape is unfamiliar" },
      ],
    },
    secondary: {
      segment: "Infrastructure capital deployers",
      size: "Deploying $500M+ into DC + power infrastructure",
      pain: "Need independent technical diligence on energization plans, technology selection, and supplier risk before committing capital",
      budget: "$100K–500K per engagement for diligence + ongoing portfolio monitoring",
      examples: [
        { name: "Blackstone / Brookfield / KKR / GIP", why: "Deploying billions into DC infra; need independent power engineering expertise to underwrite deals" },
        { name: "Sovereign wealth funds (ADIA, PIF, Mubadala)", why: "Building GW-scale DC campuses in Middle East; need turnkey energization planning" },
      ],
    },
  },

  sellTo: {
    title: "Specific first 10 targets — who we'd sell to, and why now",
    targets: [
      { name: "CoreWeave", title: "VP Infrastructure / Head of Energy", hook: "You're at ~850 MW with Bloom and scaling fast. As you diversify beyond fuel cells into engines + grid + storage, you need a unified planning and dispatch layer. We build that.", mw: "1,000+", urgency: "Now" },
      { name: "Lambda Labs", title: "CEO / VP Ops", hook: "You just raised $1.5B+ and need 100+ MW of GPU capacity online in 12 months. Your team builds AI, not power plants. We plan and procure your energization end-to-end.", mw: "100–200", urgency: "Now" },
      { name: "Vantage Data Centers", title: "SVP Development / VP Energy", hook: "You're expanding into 5 new markets globally. Each has a different power landscape, supplier set, and permitting regime. Our platform gives you a consistent energization playbook and pre-negotiated supplier access everywhere.", mw: "200–500", urgency: "Now" },
      { name: "DataBank (Digital Bridge)", title: "VP Engineering", hook: "You're building 200+ MW in Texas and Virginia. Grid queues are 4+ years in NoVA and ERCOT is complex. We cut your time-to-power by 12+ months with hybrid BTM+grid planning.", mw: "200+", urgency: "Q3 2026" },
      { name: "Together AI", title: "COO / Head of Infra", hook: "Inference is about to overtake training as the load driver. You need 50–100 MW fast, with flexible ramp. We design a multi-source energization plan that matches your variable AI load shape.", mw: "50–100", urgency: "Now" },
      { name: "Compass Datacenters", title: "SVP Power & Energy", hook: "You're going global — entering Middle East and APAC. We've mapped the supplier landscape in every target region and can compress your site selection and energization timeline.", mw: "300+", urgency: "Q3 2026" },
      { name: "Yondr Group", title: "Head of Energy", hook: "You build hyperscale for others. Your clients demand energization commitments in the lease. We give you a platform to model, procure, and guarantee power delivery timelines.", mw: "100–500", urgency: "Now" },
      { name: "Blackstone Infrastructure", title: "Managing Director, Digital Infra", hook: "You've invested $1B+ in VoltaGrid and are deploying billions more in DC. We provide independent energization diligence and ongoing portfolio power optimization across your DC holdings.", mw: "Portfolio", urgency: "Now" },
      { name: "EdgeConneX", title: "VP Energy Procurement", hook: "You operate in 50+ markets globally. Our interconnection queue tracker and supplier marketplace give your lean energy team 10x leverage across all sites.", mw: "100–300", urgency: "Q4 2026" },
      { name: "PIF / NEOM (Saudi)", title: "Program Director, Digital Infra", hook: "You're building GW-scale AI infrastructure in a market with no DC power precedent. We bring US/EU best practices, pre-negotiated supplier access (VoltaGrid, Bloom, INNIO), and a turnkey energization plan.", mw: "500–2,000", urgency: "Now" },
    ],
  },

  roadmap: [
    { phase: "P0 — Validate (Month 1–3)", color: "#38e1b0",
      items: [
        "Conduct 20 discovery calls with mid-market colo/AI operators (target list above)",
        "Validate willingness-to-pay for energization planning + procurement",
        "Sign 2–3 design partners (free/discounted Scout access in exchange for feedback + case studies)",
        "Build v0.1 of the energization planning engine (spreadsheet-grade, human-in-the-loop)",
        "Secure framework agreements with 3–5 Tier 1-2 suppliers (Bloom, INNIO, Mainspring, Caterpillar)",
      ] },
    { phase: "P1 — Scout Launch (Month 4–9)", color: "#5b8cff",
      items: [
        "Ship PowerPath Scout web platform (planning engine + supplier marketplace + queue tracker)",
        "Hire 3–5 senior power engineers (ex-utility, ex-Bechtel/B&McD, ex-hyperscaler energy teams)",
        "Close first 5 paying customers at $10K–25K/mo + procurement success fee",
        "Build proprietary dataset: pricing benchmarks, slot availability, permitting timelines",
        "Target ARR: $1.5M by month 12",
      ] },
    { phase: "P2 — Control (Month 12–24)", color: "#ffb454",
      items: [
        "Ship PowerPath Control — hybrid asset EMS for multi-source BTM sites",
        "Integrate with Bloom ServerFarm, INNIO myPlant, Tesla Autobidder, utility SCADA",
        "Upsell Control to existing Scout customers who are now operating BTM assets",
        "Add grid-services optimization (demand response, frequency regulation revenue)",
        "Target ARR: $8M by month 24",
      ] },
    { phase: "P3 — Capital (Month 24–36)", color: "#ff6b6b",
      items: [
        "Raise infrastructure fund or partner with Blackstone/Brookfield/KKR",
        "Own and operate BTM assets at customer sites under power agreements",
        "Use Scout data for site selection, Control software for operations",
        "Target: 500 MW under management, $50M+ revenue run-rate",
        "Become a software-differentiated, data-center-focused IPP",
      ] },
  ],

  competitiveEdge: {
    title: "Why us vs. alternatives",
    comparisons: [
      { alternative: "Big-4 / McKinsey energy advisory", edge: "They charge $2M for a 6-month study. We deliver a live platform with real-time supplier data, continuously updated — 10x faster, 5x cheaper, and we actually procure, not just advise." },
      { alternative: "Bloom / VoltaGrid (single-vendor)", edge: "They sell their own equipment. We're vendor-neutral and optimize across the full technology stack. The customer gets the best $/MWh and fastest time-to-power, not what one vendor has in stock." },
      { alternative: "In-house power team", edge: "Only hyperscalers can afford a 20-person power procurement team. We provide that capability as a service for $200K/yr instead of $4M/yr in fully-loaded headcount." },
      { alternative: "Traditional EPC firms", edge: "Bechtel and Burns & McDonnell build what you tell them. We figure out what to build, from whom, and in what sequence — then hand off to the EPC. We're upstream in the decision chain." },
      { alternative: "Utility account managers", edge: "Utilities want you on the grid (4+ year wait). We show you the full option set including BTM, co-location, and hybrid — many of which bypass the utility entirely." },
    ],
  },

  tam: {
    title: "Market sizing",
    rows: [
      { label: "New DC capacity to 2030", value: "~97 GW", note: "~$300B+ in power infrastructure spend" },
      { label: "Mid-market share (non-hyperscaler)", value: "~30–40%", note: "~30–40 GW = ~500 operators" },
      { label: "Addressable spend on energization services", value: "~$5–10B", note: "Planning + procurement + EMS + power agreements" },
      { label: "Scout TAM (advisory + platform)", value: "~$500M–1B/yr", note: "500 operators × $1–2M/yr avg" },
      { label: "Control TAM (EMS software)", value: "~$1–2B/yr", note: "Per-site SaaS on 30+ GW of BTM assets" },
      { label: "Capital TAM (own assets)", value: "~$10–30B+", note: "Own 1–5 GW of BTM generation" },
    ],
  },
};
